-- 0023: 붙임1 사업신청서·붙임2 사업추진계획서 통일 pt 타이포그래피 정합 +
-- 동의서 attachment_no 정규화(경영개선 track 붙임3/4) + 폐업 track 명칭 구분(붙임4 메타 중복 해소).

update public.document_templates set name='사업 신청서', attachment_no='붙임1', html_content=$html$<!doctype html><html lang="ko"><head><meta charset="utf-8"><style> @page{size:A4;margin:16mm 15mm} body{color:#000;font-size:10pt;line-height:1.5} h1{text-align:center;font-size:18pt;font-weight:800;letter-spacing:0.5px;margin:0 0 12pt} table{border-collapse:collapse;width:100%;table-layout:fixed} th,td{border:1px solid #000;padding:4pt 6pt;vertical-align:middle} th{background:#f2f2f2;font-weight:700;text-align:center;width:18%;font-size:10pt} td{text-align:left;width:32%;font-size:10pt} .sub{font-weight:400;font-size:8.5pt} .chk{line-height:1.9} .confirm{margin:12pt 2px 0;text-align:justify} .sign{margin-top:16pt;text-align:right;line-height:2.3} .sign .date{text-align:center;letter-spacing:1px;margin-bottom:3pt} .sign .who{padding-right:14pt} .foot{margin-top:12pt;text-align:left;font-weight:800;font-size:13pt} </style></head><body><h1>대전 소상공인·자영업자 재기지원(컨설팅·경영개선) 신청서</h1><table><tr><th>업 체 명</th><td>{{business_name}}</td><th>대 표 자</th><td>{{owner_name}}</td></tr><tr><th>사업자<br>등록번호</th><td>{{business_reg_no}}</td><th>사업장<br>연락처</th><td>{{phone}}</td></tr><tr><th>법인등록번호<br><span class="sub">(해당시)</span></th><td></td><th>대표<br>휴대번호</th><td>{{phone}}</td></tr><tr><th>개업연월일</th><td>{{opened_at}}</td><th>사업장형태</th><td>□ 개인 &nbsp;&nbsp; □ 법인</td></tr><tr><th>사업장 주소</th><td colspan="3">{{address}}</td></tr><tr><th>이메일</th><td colspan="3">{{email}}</td></tr><tr><th>업 태</th><td>{{business_type}}</td><th>종목/<br>주요상품</th><td>{{item}}</td></tr><tr><th>근로자수<br><span class="sub">(신청일)</span></th><td>{{employee_count}}</td><th>매출액<br><span class="sub">(2025년)</span></th><td class="rt">{{revenue_last_year}} 원</td></tr><tr><th>컨설팅<br>희망분야<br><span class="sub">(복수체크)</span></th><td colspan="3" class="chk">□ 상권 및 입지 &nbsp; □ 사업타당성 &nbsp; □ 경영진단 &nbsp; □ 마케팅 &nbsp; □ 점포운영<br>□ 고객서비스 &nbsp; □ 기술전수 &nbsp; □ 세무,노무 &nbsp; □ 메뉴개발 &nbsp; □ 기타</td></tr></table><p class="confirm">위와 같이 「대전 소상공인·자영업자 재기지원(컨설팅·경영개선)」 신청서를 제출하며 작성한 내용에 허위 사실이 없음을 확인합니다.</p><div class="sign"><p class="date">{{today}}</p><p class="who">업체명 : {{business_name}} &nbsp;&nbsp; 대표 : {{owner_name}} &nbsp; {{{sign_applicant}}} &nbsp;</p></div><p class="foot">{{institution}} 귀하</p></body></html>$html$ where template_key='business_application';

update public.document_templates set name='사업추진계획서 및 사업장 현장 사진', attachment_no='붙임2', html_content=$html$<!doctype html><html lang="ko"><head><meta charset="utf-8"><style> @page{size:A4;margin:16mm 15mm} body{color:#000;font-size:10pt;line-height:1.5} h1{text-align:center;font-size:18pt;font-weight:800;letter-spacing:0.5px;margin:0 0 12pt} table{border-collapse:collapse;width:100%;table-layout:fixed;margin-bottom:10pt} th,td{border:1px solid #000;padding:4pt 6pt;vertical-align:top} th{background:#f2f2f2;font-weight:700;text-align:center;vertical-align:middle;font-size:10pt} td{font-size:10pt} .h th{width:18%}.h td{width:32%} .big th{width:18%}.big td{height:72pt} .sub{font-weight:400;font-size:8.5pt;color:#555} .pbox{border:1px solid #000;margin:6pt 0} .pcap{background:#f2f2f2;border-bottom:1px solid #000;padding:5pt 7pt;font-weight:700;font-size:10pt} .pnote{padding:4pt 7pt;color:#555;font-size:8.5pt} .parea{height:120pt} </style></head><body><h1>대전 소상공인·자영업자 재기지원(컨설팅·경영개선) 사업추진계획서</h1><table class="h"><tr><th>업 체 명</th><td>{{business_name}}</td><th>대 표 자</th><td>{{owner_name}}</td></tr><tr><th>사업자<br>등록번호</th><td>{{business_reg_no}}</td><th>연락처</th><td>{{phone}}</td></tr><tr><th>주요업종</th><td>{{business_type}}</td><th>주요품목</th><td>{{item}}</td></tr><tr><th>이메일</th><td colspan="3">{{email}}</td></tr></table><table class="big"><tr><th>업체소개</th><td><span class="sub">* 업체현황, 기업의 특징, 장점 등</span></td></tr><tr><th>지원<br>필요성</th><td><span class="sub">* 컨설팅·경영개선 필요성, 경영상황 등</span></td></tr><tr><th>기대<br>효과</th><td><span class="sub">* 컨설팅·경영개선 지원을 통한 기대효과, 성장계획 등</span></td></tr></table><div class="pbox"><div class="pcap">경영개선 필요분야 사진</div><div class="pnote">* 경영개선이 필요한 항목에 대한 사진</div><div class="parea"></div></div><div class="pbox"><div class="pcap">사업장 외부 사진 (간판이 포함된 현재 사업장 외부 사진)</div><div class="pnote">* 업체명을 확인할 수 있는 간판 사진이 포함된 사업장 외부 사진</div><div class="parea"></div></div><div class="pbox"><div class="pcap">사업장 내부 사진 (현재 사업장 전체 내부 사진)</div><div class="pnote">* 사업장 내부 전체를 파악할 수 있는 사진</div><div class="parea"></div></div></body></html>$html$ where template_key='business_plan';

-- 동의서: 명칭에서 (붙임N) 접미사 제거 + 경영개선 track 번호 정규화
update public.document_templates set name='개인정보 수집·이용 및 제공 동의서', attachment_no='붙임3' where template_key='consent_privacy';
update public.document_templates set name='행정정보 공동이용 사전동의서', attachment_no='붙임4' where template_key='consent_admin_info';

-- 폐업정리 track: 명칭에 트랙 표기로 붙임4 메타 중복 해소(별도 공고문 서식)
update public.document_templates set name='[폐업정리] 지원 신청서' where template_key='support_application_closure';
update public.document_templates set name='[폐업정리] 완료보고서 및 지원금 신청서' where template_key='payment_application_closure';

